server:
  port: ${PORT:8080}
  
spring:
  application:
    name: security
  profiles:
    active: dev

#logging:
#  level:
#    org:
#      springframework:
#        security:
#          web:
#            FilterChainProxy: DEBUG
      
          